### ISSUE TITLE
Build error - Ubuntu

### ISSUE THREAD

**Issue by moooji** [compose/transporter#53]
When I try to build transporter on a Ubuntu box, I get the following error. Any idea, what might be wrong?

../../compose/transporter/pkg/adaptor/influxdb.go:98: undefined: client.Series
../../compose/transporter/pkg/adaptor/influxdb.go:104: i.influxClient.WriteSeries undefined (type *client.Client has no field or method WriteSeries)
../../compose/transporter/pkg/adaptor/influxdb.go:104: undefined: client.Series
../../compose/transporter/pkg/adaptor/influxdb.go:111: undefined: client.ClientConfig
../../compose/transporter/pkg/adaptor/rethinkdb.go:133: unknown gorethink.ConnectOpts field 'IdleTimeout' in struct literal

**Comment by codepope** [comment]
The InfluxDB developers are in the middle of a big rework on the way to version 0.90 which means they broke the master tree of their github repository.

To fix it go to src/github.com/influxdb/influxdb
and do

git checkout tags/v0.8.8

Which will switch the influxdb tree to 0.8.8 and things should build then.

**Comment by mikeolivieri** [comment]
I ran into the same build error with InfluxDB, checking out 0.8.8 got me passed the influxdb errors, but still blocked on `./compose/transporter/pkg/adaptor/rethinkdb.go:133: unknown gorethink.ConnectOpts field 'IdleTimeout' in struct literal`. Is there a similar fix for rethinkdb? Thanks.

**Comment by nstott** [comment]
Hi, Yeah, there was a change pushed a few days ago that effected rethink's connectops
https://github.com/dancannon/gorethink/blob/master/CHANGELOG.md#v060---1-feb-2015
I'll push a change soon
